# Generated by Django 6.0.6 on 2026-06-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('wishlist', 'Хочу прочитать'), ('reading', 'Читаю'), ('finished', 'Прочитано')], default='wishlist', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Начал читать')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Закончил читать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
